
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: vibes 
  port: 5432
  host: localhost

development:
  <<: *default
  database: homatri_development

test:
  <<: *default
  database: homatri_test
  user: homatri
  password: homatri

production:
  <<: *default
  database: <%= ENV['HOMATRI_DATABASE_NAME'] %>
  username: <%= ENV['HOMATRI_DATABASE_USER'] %>
  password: <%= ENV['HOMATRI_DATABASE_PASSWORD'] %>
